services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      args: { UID: 1000, GID: 1000 }
    working_dir: /rails
    command: bash -lc "bin/rails s -b 0.0.0.0 -p 3000"
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/rails
  sidekiq:
    build: .
    working_dir: /rails
    container_name: sidekiq
    command: bash -lc "bundle exec sidekiq -C config/sidekiq.yml"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/rails

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
